language: python

python:
  - 2.7
  - 3.5

sudo: true

services:
  - docker

before_install:
  - pwd
  - echo $PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      export DOCKER_ENV=/opt/anaconda;
    else
      export DOCKER_ENV=/opt/anaconda/envs/py3;
    fi
  - pushd continuous_integration
  - docker-compose up
  - export CONTAINER_ID="continuousintegration_rambling_1"
  - sleep 80  # Wait for namenode and datanode

install:
  - pwd
  - echo $DOCKER_ENV
  - docker exec -it $CONTAINER_ID $DOCKER_ENV/bin/python setup.py install

script:
  - pwd
  - docker exec -it $CONTAINER_ID $DOCKER_ENV/bin/py.test /rambling/rambling -s -vv
