language: python

python:
  - 2.7
  - 3.6

sudo: true

services:
  - docker

before_install:
  - docker run --name knit_test -d -v $PWD:/knit mdurant/hadoop
  - export CONTAINER_ID=`docker ps | grep knit_test | awk '{print $1}'`
  - sleep 20

install:
  - docker exec -it $CONTAINER_ID conda create -y -n test python=$TRAVIS_PYTHON_VERSION pytest dask distributed

script:
  - docker exec -it $CONTAINER_ID bash /knit/continuous_integration/simple_test.sh

after_success:
  # - docker exec -it $CONTAINER_ID bash -c "export TRAVIS=$TRAVIS && export TRAVIS_JOB_ID=$TRAVIS_JOB_ID && TRAVIS_BRANCH=$TRAVIS_BRANCH && /knit/continuous_integration/coverage_upload.sh"
  - docker kill $CONTAINER_ID
