package:
    name: knit
    version: 0.2

source:
    path: ../

requirements:
    build:
        - python
        - apache-maven
        - java-jdk [linux]
    run:
        - python
        - lxml
        - requests
        - py4j

about:
  home: https://github.com/dask/knit
  license: BSD
  summary: Python interface to Scala for interacting with YARN
